repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: "api"
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: "api"
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: "api"
        args: [--config=./api/.flake8]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        files: "api"
        args: [-lll]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        files: "api"
        entry: bash -c 'cd api && mypy --ignore-missing-imports --config-file=./mypy.ini .'
        additional_dependencies:
          - djangorestframework-stubs
          - django-stubs
          - daphne
          - djangorestframework
          - drf-spectacular
          - psycopg2-binary
