services:
  db:
    image: postgres:16
    restart: on-failure
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=atb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
