# Generated by Django 5.0.6 on 2024-08-01 18:49

from decimal import Decimal

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import atb.bike.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cassette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100)),
                (
                    "gtin",
                    models.PositiveBigIntegerField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(99999999999999)
                        ],
                    ),
                ),
                ("mpn", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="private",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gears",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(), size=None
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bike.brand",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100)),
                (
                    "gtin",
                    models.PositiveBigIntegerField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(99999999999999)
                        ],
                    ),
                ),
                ("mpn", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="private",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "front_center",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                ("wheelbase", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("spacers", models.PositiveSmallIntegerField(blank=True, default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bike.brand",
                    ),
                ),
                (
                    "cassette",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bike.cassette",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chainring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gears",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(), size=None
                    ),
                ),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chainring",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.PositiveSmallIntegerField()),
                ("q_factor", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crank",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalHeadset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upper_cup_stack_height", models.PositiveSmallIntegerField()),
                ("lower_cup_stack_height", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_headset",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset", models.PositiveSmallIntegerField()),
                ("crown_to_axle", models.PositiveSmallIntegerField()),
                ("steerer_tube", models.PositiveSmallIntegerField()),
                ("travel", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fork",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reach", models.PositiveSmallIntegerField()),
                ("stack", models.PositiveSmallIntegerField()),
                ("chainstay", models.PositiveSmallIntegerField()),
                ("head_tube", models.PositiveSmallIntegerField()),
                (
                    "head_tube_angle",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "actual_seat_tube_angle",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "effective_seat_tube_angle",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                ("seat_tube", models.PositiveSmallIntegerField()),
                ("bb_drop", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Handlebar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.PositiveSmallIntegerField()),
                ("rise", models.PositiveSmallIntegerField()),
                ("reach", models.PositiveSmallIntegerField()),
                (
                    "backsweep",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "upsweep",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "drop_flare",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "drop_flare_out",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                ("drop_width", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handlebar",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("size", models.CharField(blank=True, max_length=100)),
                (
                    "gtin",
                    models.PositiveBigIntegerField(
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(99999999999999)
                        ],
                    ),
                ),
                ("mpn", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("private", "Private"),
                            ("public", "Public"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="private",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stack_height", models.PositiveSmallIntegerField()),
                ("pedal_center", models.PositiveSmallIntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bike.brand",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bike",
            name="pedal",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="bike.pedal"
            ),
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inseam", models.PositiveSmallIntegerField()),
                ("upper_leg", models.PositiveSmallIntegerField()),
                ("foot", models.PositiveSmallIntegerField()),
                ("arm", models.PositiveSmallIntegerField()),
                ("spine", models.PositiveSmallIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Saddle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saddle",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seatpost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.PositiveSmallIntegerField()),
                ("offset", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seatpost",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.PositiveSmallIntegerField()),
                (
                    "angle",
                    atb.bike.models.AngleField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                ("steerer_height", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stem",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TireSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_diameter", models.PositiveSmallIntegerField()),
                ("front_width", models.PositiveSmallIntegerField()),
                ("rear_diameter", models.PositiveSmallIntegerField()),
                ("rear_width", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tireset",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WheelSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front_diameter", models.PositiveSmallIntegerField()),
                ("rear_diameter", models.PositiveSmallIntegerField()),
                (
                    "bike",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wheelset",
                        to="bike.bike",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cassette",
            constraint=models.UniqueConstraint(
                fields=("brand", "mpn", "size"),
                name="bike_cassette_unique_brand_mpn_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="pedal",
            constraint=models.UniqueConstraint(
                fields=("brand", "mpn", "size"), name="bike_pedal_unique_brand_mpn_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="bike",
            constraint=models.UniqueConstraint(
                fields=("brand", "mpn", "size"), name="bike_bike_unique_brand_mpn_size"
            ),
        ),
    ]
