const tumbleWeedBikes = [
  {
    id: "tw-stargazer-s",
    name: "Stargazer S",
    geometry: {
      reach: 365,
      stack: 574,
      headTube: 115 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73.5,
      effectiveSeatTubeAngle: 73.5,
      seatTube: 380,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-m",
    name: "Stargazer M",
    geometry: {
      reach: 372,
      stack: 597,
      headTube: 140 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73,
      effectiveSeatTubeAngle: 73,
      seatTube: 430,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-e-m",
    name: "Stargazer Extra M",
    geometry: {
      reach: 382,
      stack: 630,
      headTube: 175 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73,
      effectiveSeatTubeAngle: 73,
      seatTube: 460,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-l",
    name: "Stargazer L",
    geometry: {
      reach: 389,
      stack: 653,
      headTube: 200 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 72.5,
      effectiveSeatTubeAngle: 72.5,
      seatTube: 490,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-xl",
    name: "Stargazer XL",
    geometry: {
      reach: 403,
      stack: 680,
      headTube: 220 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 72.5,
      effectiveSeatTubeAngle: 72.5,
      seatTube: 545,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
];

const salsaBikes = [
  {
    id: "salsa-cutthroat-52",
    name: "Cutthroat 52cm",
    geometry: {
      reach: 358,
      stack: 585,
      headTube: 90,
      headTubeAngle: 69.0,
      chainStay: 445,
      actualSeatTubeAngle: 74.5,
      effectiveSeatTubeAngle: 74.5,
      seatTube: 356,
      bottomBracketDrop: 70,
      frontCenter: 0,
      wheelBase: 1050,
      forkAxleToCrown: 483,
      forkOffset: 51,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 60,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 440,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 56,
      tireRearWidth: 56,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "salsa-cutthroat-54",
    name: "Cutthroat 54cm",
    geometry: {
      reach: 373,
      stack: 592,
      headTube: 98,
      headTubeAngle: 69.0,
      chainStay: 445,
      actualSeatTubeAngle: 74.25,
      effectiveSeatTubeAngle: 74.25,
      seatTube: 419,
      bottomBracketDrop: 70,
      frontCenter: 0,
      wheelBase: 1068,
      forkAxleToCrown: 483,
      forkOffset: 51,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 70,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 460,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 56,
      tireRearWidth: 56,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "salsa-cutthroat-56",
    name: "Cutthroat 56cm",
    geometry: {
      reach: 385,
      stack: 620,
      headTube: 127,
      headTubeAngle: 69.0,
      chainStay: 445,
      actualSeatTubeAngle: 74.25,
      effectiveSeatTubeAngle: 74.25,
      seatTube: 508,
      bottomBracketDrop: 70,
      frontCenter: 0,
      wheelBase: 1090,
      forkAxleToCrown: 483,
      forkOffset: 51,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 175,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 80,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 460,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 56,
      tireRearWidth: 56,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "salsa-cutthroat-58",
    name: "Cutthroat 58cm",
    geometry: {
      reach: 395,
      stack: 645,
      headTube: 154,
      headTubeAngle: 69.0,
      chainStay: 445,
      actualSeatTubeAngle: 74.0,
      effectiveSeatTubeAngle: 74.0,
      seatTube: 559,
      bottomBracketDrop: 70,
      frontCenter: 0,
      wheelBase: 1110,
      forkAxleToCrown: 483,
      forkOffset: 51,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 175,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 80,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 460,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 56,
      tireRearWidth: 56,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "salsa-cutthroat-60",
    name: "Cutthroat 60cm",
    geometry: {
      reach: 406,
      stack: 664,
      headTube: 175,
      headTubeAngle: 69.0,
      chainStay: 445,
      actualSeatTubeAngle: 73.75,
      effectiveSeatTubeAngle: 73.75,
      seatTube: 584,
      bottomBracketDrop: 70,
      frontCenter: 0,
      wheelBase: 1129,
      forkAxleToCrown: 483,
      forkOffset: 51,
      forkTravel: 0,
      forkSag: 0,
      crankLength: 175,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 90,
      stemAngle: 7,
      seatOffset: 0,
      handlebarWidth: 460,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 56,
      tireRearWidth: 56,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
];

const bikeRegistry = {
  Tumbleweed: [...tumbleWeedBikes],
  Salsa: [...salsaBikes],
};

export default bikeRegistry;
