const tumbleWeedBikes = [
  {
    id: "tw-stargazer-s",
    name: "Stargazer S",
    geometry: {
      reach: 365,
      stack: 574,
      headTube: 115 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73.5,
      effectiveSeatTubeAngle: 73.5,
      seatTube: 380,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      stemSteererHeight: 40,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-m",
    name: "Stargazer M",
    geometry: {
      reach: 372,
      stack: 597,
      headTube: 140 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73,
      effectiveSeatTubeAngle: 73,
      seatTube: 430,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      stemSteererHeight: 40,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-e-m",
    name: "Stargazer Extra M",
    geometry: {
      reach: 382,
      stack: 630,
      headTube: 175 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 73,
      effectiveSeatTubeAngle: 73,
      seatTube: 460,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      stemSteererHeight: 40,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-l",
    name: "Stargazer L",
    geometry: {
      reach: 389,
      stack: 653,
      headTube: 200 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 72.5,
      effectiveSeatTubeAngle: 72.5,
      seatTube: 490,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      stemSteererHeight: 40,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
  {
    id: "tw-stargazer-xl",
    name: "Stargazer XL",
    geometry: {
      reach: 403,
      stack: 680,
      headTube: 220 + 12,
      headTubeAngle: 69,
      chainStay: 450,
      actualSeatTubeAngle: 72.5,
      effectiveSeatTubeAngle: 72.5,
      seatTube: 545,
      bottomBracketDrop: 63,
      frontCenter: 0,
      wheelBase: 0,
      forkAxleToCrown: 440,
      forkOffset: 55,
      forkTravel: 0,
      crankLength: 170,
      crankQFactor: 172,
      spacers: 100,
      stemLength: 100,
      stemAngle: 7,
      stemSteererHeight: 40,
      seatOffset: 0,
      handlebarWidth: 420,
      handlebarReach: 75,
      handlebarRise: 5,
      tireFrontWidth: 54,
      tireRearWidth: 54,
      wheelFrontDiameter: 622,
      wheelRearDiameter: 622,
    },
  },
];

const bikeRegistry = [...tumbleWeedBikes];
export default bikeRegistry;
