name: app

on:
  pull_request:
    paths:
      - "app/**"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Install modules
        run: npm install
        working-directory: app
      - name: Run linter
        run: npm run lint
        working-directory: app

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Install modules
        run: npm install
        working-directory: app
      - name: Run tests
        run: npm run test
        working-directory: app
